(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fallbackImgs=['https://images.pexels.com/photos/7216290/pexels-photo-7216290.jpeg?auto=compress&cs=tinysrgb&w=1000','https://images.pexels.com/photos/7772650/pexels-photo-7772650.jpeg?auto=compress&cs=tinysrgb&w=1000','https://images.pexels.com/photos/3736280/pexels-photo-3736280.jpeg?auto=compress&cs=tinysrgb&w=1000'];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const statusName=s=>({pending:'Pendiente',confirmed:'Confirmada',completed:'Realizada',cancelled:'Cancelada'}[s]||s);
const methodName=s=>({cash:'Efectivo',card:'Tarjeta',transfer:'Transferencia',other:'Otro'}[s]||s);
let csrf='',services=[],appointments=[],payments=[],profile=null,editId=null,calendarCursor=new Date();
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function asDate(v){return new Date(String(v||'').replace(' ','T'))}
function fmt(v){try{return new Intl.DateTimeFormat('es-MX',{weekday:'long',day:'numeric',month:'long',hour:'numeric',minute:'2-digit'}).format(asDate(v))}catch{return String(v||'')}}
function money(v){return '$'+Number(v||0).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2})}
async function req(url,opt={}){const r=await fetch(url,{cache:'no-store',credentials:'same-origin',...opt});const d=await r.json().catch(()=>({}));if(r.status===401){location.replace('../admin/login.html');throw new Error('Sesión requerida')}if(!r.ok)throw new Error(d.error||'No se pudo completar');return d}
async function mutate(url,method,payload){return req(url,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(payload)})}
function showTab(name){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${name}`));window.scrollTo({top:0,behavior:'smooth'})}
$$('.tab').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));
function renderCalendar(){const box=$('#calendarDays'),title=$('#calTitle');if(!box||!title)return;const first=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth(),1),last=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,0),today=localDate();title.textContent=new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric'}).format(first);const offset=(first.getDay()+6)%7;let html='';for(let i=0;i<offset;i++)html+='<span></span>';for(let d=1;d<=last.getDate();d++){const dt=new Date(first.getFullYear(),first.getMonth(),d),key=localDate(dt),past=key<today;html+=`<button type="button" class="day${key===today?' today':''}" data-date="${key}" ${past?'disabled':''}>${d}</button>`}box.innerHTML=html;box.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>selectDate(b.dataset.date));}
function selectDate(date){$$('.day').forEach(b=>b.classList.toggle('selected',b.dataset.date===date));const ds=$('#dateSelect');if(ds)ds.innerHTML=`<option value="${date}">${new Intl.DateTimeFormat('es-MX',{weekday:'long',day:'numeric',month:'long'}).format(new Date(date+'T12:00:00'))}</option>`;loadSlots();}
$('#prevMonth')?.addEventListener('click',()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1);renderCalendar()});
$('#nextMonth')?.addEventListener('click',()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1);renderCalendar()});
async function loadSlots(){const sid=$('#serviceSelect')?.value,date=$('#dateSelect')?.value,t=$('#timeSelect');if(!t)return;if(!sid||!date){t.innerHTML='<option value="">Elige tratamiento y día</option>';return}t.innerHTML='<option value="">Consultando…</option>';try{const d=await req(`../backend/api/availability.php?service_id=${encodeURIComponent(sid)}&date=${encodeURIComponent(date)}`);t.innerHTML='<option value="">Selecciona una hora</option>'+(d.data||[]).map(x=>`<option value="${esc(x.time)}">${esc(x.time)}</option>`).join('');if(!(d.data||[]).length)t.innerHTML='<option value="">Sin horarios disponibles</option>'}catch(e){t.innerHTML='<option value="">No disponible</option>'}}
$('#serviceSelect')?.addEventListener('change',loadSlots);
function renderServices(){const select=$('#serviceSelect');if(select)select.innerHTML='<option value="">Selecciona un tratamiento</option>'+services.map(s=>`<option value="${Number(s.id)}">${esc(s.name)} · ${Number(s.duration_minutes)||60} min</option>`).join('');const strip=$('#serviceStrip');if(strip)strip.innerHTML=services.length?services.map((s,i)=>`<button type="button" class="service-preview" data-service="${Number(s.id)}"><img src="${esc(s.image_url||fallbackImgs[i%fallbackImgs.length])}" alt="${esc(s.name)}"><div><strong>${esc(s.name)}</strong><span>${Number(s.duration_minutes)||60} min${s.price!==null&&s.price!==undefined?` · ${money(s.price)}`:''}</span></div></button>`).join(''):'<p class="empty">No hay servicios disponibles.</p>';strip?.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{if(select)select.value=b.dataset.service;showTab('book');loadSlots()});}
function canChange(a){return ['pending','confirmed'].includes(a.status)&&asDate(a.starts_at)>new Date()}
function appointmentCard(a){const actions=canChange(a)?`<div class="actions"><button type="button" class="secondary" data-reschedule="${Number(a.id)}">Reprogramar</button><button type="button" class="danger" data-cancel="${Number(a.id)}">Cancelar</button></div>`:'';return `<article class="appointment-card"><header><div><h3>${esc(a.service_name||'Servicio')}</h3><p>${esc(fmt(a.starts_at))}${a.manager_name?` · ${esc(a.manager_name)}`:''}</p></div><span class="pill">${esc(statusName(a.status))}</span></header>${actions}</article>`}
function wireAppointmentActions(root=document){root.querySelectorAll('[data-reschedule]').forEach(b=>b.onclick=()=>startReschedule(Number(b.dataset.reschedule)));root.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>cancelAppointment(Number(b.dataset.cancel)))}
function renderAppointments(){const list=$('#appointmentsList');if(list){list.innerHTML=appointments.length?appointments.map(appointmentCard).join(''):'<p class="empty">Aún no tienes citas.</p>';wireAppointmentActions(list)}const upcoming=appointments.filter(canChange).sort((a,b)=>String(a.starts_at).localeCompare(String(b.starts_at)));const n=upcoming[0],box=$('#nextAppointment');if(box){box.innerHTML=n?`<div class="next"><strong>${esc(n.service_name||'Servicio')}</strong><span>${esc(fmt(n.starts_at))}${n.manager_name?` · ${esc(n.manager_name)}`:''}</span><div class="actions"><button class="secondary" data-reschedule="${Number(n.id)}">Reprogramar</button><button class="danger" data-cancel="${Number(n.id)}">Cancelar</button></div></div>`:'<p class="empty">No tienes una cita próxima.</p>';wireAppointmentActions(box)}const rem=$('#reminder');if(rem){if(n){const hrs=(asDate(n.starts_at)-new Date())/36e5;rem.textContent=hrs>0&&hrs<=24?'✦ Recordatorio: tu cita es en menos de 24 horas.':''}else rem.textContent=''}renderSummary();}
function renderSummary(){const stats=$('#summaryStats');if(!stats)return;const future=appointments.filter(canChange).length;stats.innerHTML=`<div class="detail"><small>CITAS PRÓXIMAS</small><b>${future}</b></div><div class="detail"><small>SERVICIOS DISPONIBLES</small><b>${services.length}</b></div><div class="detail"><small>PAGOS REGISTRADOS</small><b>${payments.length}</b></div>`}
function startReschedule(id){const a=appointments.find(x=>Number(x.id)===id);if(!a)return;editId=id;$('#editBanner')?.classList.add('show');if($('#editText'))$('#editText').textContent=`Reprogramando: ${a.service_name||'cita'}`;if($('#bookingHeading'))$('#bookingHeading').innerHTML='Reprograma tu <em>cita.</em>';if($('#bookButton'))$('#bookButton').textContent='Guardar nueva fecha';if($('#serviceSelect'))$('#serviceSelect').value=String(a.service_id||'');const d=String(a.starts_at||'').slice(0,10);if(d){const dt=new Date(d+'T12:00:00');calendarCursor=new Date(dt.getFullYear(),dt.getMonth(),1);renderCalendar();selectDate(d)}showTab('book')}
function stopReschedule(){editId=null;$('#editBanner')?.classList.remove('show');if($('#bookingHeading'))$('#bookingHeading').innerHTML='Agenda tu <em>cita.</em>';if($('#bookButton'))$('#bookButton').textContent='Solicitar cita'}
$('#cancelEdit')?.addEventListener('click',stopReschedule);
async function cancelAppointment(id){if(!confirm('¿Quieres cancelar esta cita?'))return;try{await mutate('../backend/api/appointments.php','PATCH',{id,action:'cancel'});await loadAppointments()}catch(e){alert(e.message)}}
function renderProfile(){const box=$('#profile');if(!box)return;box.innerHTML=profile?`<div class="detail"><small>NOMBRE</small><b>${esc(profile.name||'—')}</b></div><div class="detail"><small>WHATSAPP</small><b>${esc(profile.phone||'—')}</b></div><div class="detail"><small>CORREO</small><b>${esc(profile.email||'—')}</b></div>`:'<p class="empty">No encontramos tu ficha.</p>'}
function renderPayments(){const box=$('#paymentsList');if(!box)return;box.innerHTML=payments.length?payments.map(p=>`<div class="payment-row"><span>${esc(p.service_name||'Pago')}</span><b>${money(p.amount)}</b><small>${esc(methodName(p.method))} · ${esc(statusName(p.status))}</small><small>${esc(String(p.paid_at||p.created_at||'').slice(0,16))}</small></div>`).join(''):'<p class="empty">No hay pagos registrados.</p>';renderSummary()}
async function loadAppointments(){try{appointments=(await req('../backend/api/appointments.php')).data||[];renderAppointments()}catch(e){const list=$('#appointmentsList');if(list)list.innerHTML=`<p class="empty">${esc(e.message)}</p>`;const n=$('#nextAppointment');if(n)n.innerHTML=`<p class="empty">${esc(e.message)}</p>`}}
async function loadAll(){const auth=await req('../backend/api/auth.php?action=me');if(auth.user?.role!=='client'){location.replace('../admin/');return}csrf=auth.user.csrf_token||'';if($('#firstName'))$('#firstName').textContent=(auth.user.name||'bienvenida').split(' ')[0]+'.';const tasks=[
 req('../backend/api/clients.php').then(d=>{profile=d.data?.[0]||null;renderProfile()}).catch(e=>{$('#profile').innerHTML=`<p class="empty">${esc(e.message)}</p>`}),
 req('../backend/api/services.php?include_archived=0').then(d=>{services=d.data||[];renderServices();renderSummary()}).catch(e=>{$('#serviceStrip').innerHTML=`<p class="empty">${esc(e.message)}</p>`}),
 req('../backend/api/payments.php').then(d=>{payments=d.data||[];renderPayments()}).catch(e=>{$('#paymentsList').innerHTML=`<p class="empty">${esc(e.message)}</p>`}),
 loadAppointments()
 ];await Promise.allSettled(tasks);renderCalendar();}
$('#bookingForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),status=$('#bookingStatus'),date=fd.get('date'),time=fd.get('time'),service=Number(fd.get('service_id'));if(!date||!time||!service){status.textContent='Selecciona tratamiento, día y horario';status.className='statusmsg error';return}status.textContent='Guardando…';try{const payload={service_id:service,starts_at:`${date} ${time}:00`};if(editId){payload.id=editId;await mutate('../backend/api/appointments.php','PATCH',payload);status.textContent='Cita reprogramada ✓';stopReschedule()}else{await mutate('../backend/api/appointments.php','POST',payload);status.textContent='Cita solicitada ✓'}status.className='statusmsg success';await loadAppointments();await loadSlots()}catch(err){status.textContent=err.message;status.className='statusmsg error'}});
$('#logout')?.addEventListener('click',async()=>{await mutate('../backend/api/auth.php?action=logout','POST',{}).catch(()=>{});location.replace('../admin/login.html')});
loadAll().catch(()=>location.replace('../admin/login.html'));
})();
