<?php

declare(strict_types=1);
require_once __DIR__.'/_bootstrap.php';
$pdo=db();$method=$_SERVER['REQUEST_METHOD']??'GET';$user=requireAuth();
const CLIENT_OPEN_TIME='08:00:00';const CLIENT_CLOSE_TIME='16:00:00';
function strictDate(string $v):?DateTimeImmutable{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))return null;[$y,$m,$d]=array_map('intval',explode('-',$v));if(!checkdate($m,$d,$y))return null;return new DateTimeImmutable($v.' 00:00:00',new DateTimeZone('America/Cancun'));}
function strictDateTime(string $v):?DateTimeImmutable{if(!preg_match('/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/',$v))return null;$d=DateTimeImmutable::createFromFormat('!Y-m-d H:i:s',$v,new DateTimeZone('America/Cancun'));return $d&&$d->format('Y-m-d H:i:s')===$v?$d:null;}
function entityId(mixed $v):int|false{return filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);}
function ensureClient(PDO $pdo,int $id,bool $allowArchived=false):void{$s=$pdo->prepare('SELECT active FROM clients WHERE id=:id');$s->execute(['id'=>$id]);$a=$s->fetchColumn();if($a===false)respond(['error'=>'El cliente no existe'],422);if(!$allowArchived&&(int)$a!==1)respond(['error'=>'El cliente está archivado'],422);}
function serviceDuration(PDO $pdo,int $id,bool $allowInactive=false):int{$s=$pdo->prepare('SELECT active,duration_minutes FROM services WHERE id=:id');$s->execute(['id'=>$id]);$r=$s->fetch();if(!$r)respond(['error'=>'El servicio no existe'],422);if(!$allowInactive&&(int)$r['active']!==1)respond(['error'=>'El servicio está inactivo'],422);return max(5,(int)$r['duration_minutes']);}
function ensureBusinessHours(DateTimeImmutable $start,int $duration):void{$open=new DateTimeImmutable($start->format('Y-m-d').' '.CLIENT_OPEN_TIME,new DateTimeZone('America/Cancun'));$close=new DateTimeImmutable($start->format('Y-m-d').' '.CLIENT_CLOSE_TIME,new DateTimeZone('America/Cancun'));if($start<$open||$start->modify('+'.$duration.' minutes')>$close)respond(['error'=>'Las reservas en línea están disponibles de 8:00 a. m. a 4:00 p. m. y el tratamiento debe terminar antes del cierre.'],422);}
function ensureManager(PDO $pdo,?int $id):void{if($id===null)return;$s=$pdo->prepare("SELECT 1 FROM users WHERE id=:id AND role='operator' AND active=1");$s->execute(['id'=>$id]);if(!$s->fetchColumn())respond(['error'=>'Gestor inválido o inactivo'],422);}
function hasConflict(PDO $pdo,DateTimeImmutable $start,int $duration,?int $managerId,?int $excludeId=null):bool{$end=$start->modify('+'.$duration.' minutes');$sql="SELECT a.id FROM appointments a JOIN services s ON s.id=a.service_id WHERE a.status IN ('pending','confirmed') AND a.starts_at<:end AND DATE_ADD(a.starts_at,INTERVAL s.duration_minutes MINUTE)>:start";$params=['end'=>$end->format('Y-m-d H:i:s'),'start'=>$start->format('Y-m-d H:i:s')];if($managerId!==null){$sql.=' AND (a.manager_user_id=:manager OR a.manager_user_id IS NULL)';$params['manager']=$managerId;}else{$sql.=' AND a.manager_user_id IS NULL';}if($excludeId!==null){$sql.=' AND a.id<>:exclude';$params['exclude']=$excludeId;}$sql.=' LIMIT 1';$s=$pdo->prepare($sql);$s->execute($params);return (bool)$s->fetchColumn();}
function chooseManager(PDO $pdo,DateTimeImmutable $start,int $duration,?int $excludeId=null):?int{$rows=$pdo->query("SELECT id FROM users WHERE role='operator' AND active=1 ORDER BY name")->fetchAll();foreach($rows as $r){$id=(int)$r['id'];if(!hasConflict($pdo,$start,$duration,$id,$excludeId))return $id;}if(!$rows&&!hasConflict($pdo,$start,$duration,null,$excludeId))return null;return -1;}
$select="SELECT a.id,a.starts_at,a.status,a.notes,a.manager_user_id,c.id client_id,c.name client_name,c.phone,c.active client_active,s.id service_id,s.name service_name,s.duration_minutes,s.active service_active,u.name manager_name FROM appointments a JOIN clients c ON c.id=a.client_id JOIN services s ON s.id=a.service_id LEFT JOIN users u ON u.id=a.manager_user_id";
if($method==='GET'){
 $isClient=$user['role']==='client';if(!$isClient)requirePermission('appointments.view');$date=trim((string)($_GET['date']??''));$month=trim((string)($_GET['month']??''));$nextFrom=trim((string)($_GET['next_from']??''));$clientRaw=trim((string)($_GET['client_id']??''));$idRaw=trim((string)($_GET['id']??''));$where=[];$params=[];$limit=500;
 if($idRaw!==''){$id=entityId($idRaw);if($id===false)respond(['error'=>'Cita inválida'],422);$where[]='a.id=:id';$params['id']=$id;$limit=1;}elseif($nextFrom!==''){$from=strictDateTime($nextFrom);if(!$from)respond(['error'=>'Fecha inválida'],422);$where[]='a.starts_at>=:from';$where[]="a.status IN ('pending','confirmed')";$params['from']=$from->format('Y-m-d H:i:s');$limit=max(1,min(20,(int)($_GET['limit']??1)));}elseif($date!==''){$start=strictDate($date);if(!$start)respond(['error'=>'Fecha inválida'],422);$end=$start->modify('+1 day');$where[]='a.starts_at>=:start AND a.starts_at<:end';$params+=['start'=>$start->format('Y-m-d H:i:s'),'end'=>$end->format('Y-m-d H:i:s')];}elseif($month!==''){if(!preg_match('/^(\d{4})-(\d{2})$/',$month,$p)||(int)$p[2]<1||(int)$p[2]>12)respond(['error'=>'Mes inválido'],422);$start=new DateTimeImmutable(sprintf('%04d-%02d-01 00:00:00',(int)$p[1],(int)$p[2]),new DateTimeZone('America/Cancun'));$end=$start->modify('first day of next month');$where[]='a.starts_at>=:start AND a.starts_at<:end';$params+=['start'=>$start->format('Y-m-d H:i:s'),'end'=>$end->format('Y-m-d H:i:s')];}
 if($isClient){$cid=(int)($user['client_id']??0);if($cid<1)respond(['error'=>'Cuenta sin ficha de cliente'],403);$where[]='a.client_id=:client_id';$params['client_id']=$cid;$clientRaw=(string)$cid;$limit=min($limit,100);}elseif($clientRaw!==''){$cid=entityId($clientRaw);if($cid===false)respond(['error'=>'Cliente inválido'],422);$where[]='a.client_id=:client_id';$params['client_id']=$cid;$limit=min($limit,100);}
 $sql=$select.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY a.starts_at '.($clientRaw!==''?'DESC':'ASC').' LIMIT '.$limit;$s=$pdo->prepare($sql);$s->execute($params);$rows=$s->fetchAll();if($isClient)foreach($rows as &$r){unset($r['notes'],$r['phone']);}respond(['data'=>$rows]);
}
if($method==='POST'){
 $d=jsonInput();$isClient=$user['role']==='client';if($isClient){requireFields($d,['service_id','starts_at']);$clientId=(int)($user['client_id']??0);if($clientId<1)respond(['error'=>'Cuenta sin ficha de cliente'],403);$status='pending';$notes=null;}else{requirePermission('appointments.create');requireFields($d,['client_id','service_id','starts_at']);$clientId=entityId($d['client_id']);if($clientId===false)respond(['error'=>'Cliente inválido'],422);$status=(string)($d['status']??'pending');if(!in_array($status,['pending','confirmed','completed','cancelled'],true))respond(['error'=>'Estado inválido'],422);$notes=trim((string)($d['notes']??''));}
 $serviceId=entityId($d['service_id']??null);$start=strictDateTime(trim((string)($d['starts_at']??'')));if($serviceId===false||!$start)respond(['error'=>'Servicio, fecha u hora inválidos'],422);ensureClient($pdo,$clientId,false);$duration=serviceDuration($pdo,$serviceId,false);
 if($isClient){if($start<=new DateTimeImmutable('now',new DateTimeZone('America/Cancun')))respond(['error'=>'La cita debe ser futura'],422);ensureBusinessHours($start,$duration);$managerId=chooseManager($pdo,$start,$duration);if($managerId===-1)respond(['error'=>'Ese horario ya no está disponible'],409);}else{$managerRaw=$d['manager_user_id']??null;$managerId=$managerRaw===null||$managerRaw===''?null:entityId($managerRaw);if($managerId===false)respond(['error'=>'Gestor inválido'],422);ensureManager($pdo,$managerId);if(in_array($status,['pending','confirmed'],true)&&hasConflict($pdo,$start,$duration,$managerId))respond(['error'=>'Ese gestor ya tiene una cita en ese horario'],409);}
 $s=$pdo->prepare('INSERT INTO appointments(client_id,service_id,manager_user_id,starts_at,status,notes) VALUES(:client,:service,:manager,:starts,:status,:notes)');$s->execute(['client'=>$clientId,'service'=>$serviceId,'manager'=>$managerId,'starts'=>$start->format('Y-m-d H:i:s'),'status'=>$status,'notes'=>$notes!==''?$notes:null]);respond(['id'=>(int)$pdo->lastInsertId(),'status'=>$status],201);
}
if($method==='PATCH'){
 $d=jsonInput();$id=entityId($d['id']??null);if($id===false)respond(['error'=>'Cita inválida'],422);$s=$pdo->prepare('SELECT client_id,service_id,manager_user_id,starts_at,status,notes FROM appointments WHERE id=:id');$s->execute(['id'=>$id]);$cur=$s->fetch();if(!$cur)respond(['error'=>'La cita no existe'],404);
 $isClient=$user['role']==='client';if($isClient){if((int)$cur['client_id']!==(int)($user['client_id']??0))respond(['error'=>'No puedes modificar esta cita'],403);if(!in_array($cur['status'],['pending','confirmed'],true))respond(['error'=>'Esta cita ya no puede modificarse'],409);$oldStart=new DateTimeImmutable((string)$cur['starts_at'],new DateTimeZone('America/Cancun'));if($oldStart<=new DateTimeImmutable('now',new DateTimeZone('America/Cancun')))respond(['error'=>'La cita ya comenzó o pasó'],409);if(($d['action']??'')==='cancel'){$pdo->prepare("UPDATE appointments SET status='cancelled' WHERE id=:id")->execute(['id'=>$id]);respond(['ok'=>true,'status'=>'cancelled']);}$serviceId=isset($d['service_id'])?entityId($d['service_id']):(int)$cur['service_id'];$start=isset($d['starts_at'])?strictDateTime(trim((string)$d['starts_at'])):$oldStart;if($serviceId===false||!$start)respond(['error'=>'Datos inválidos'],422);if($start<=new DateTimeImmutable('now',new DateTimeZone('America/Cancun')))respond(['error'=>'La cita debe ser futura'],422);$duration=serviceDuration($pdo,$serviceId,false);ensureBusinessHours($start,$duration);$managerId=chooseManager($pdo,$start,$duration,$id);if($managerId===-1)respond(['error'=>'Ese horario ya no está disponible'],409);$pdo->prepare("UPDATE appointments SET service_id=:service,manager_user_id=:manager,starts_at=:starts,status='pending' WHERE id=:id")->execute(['service'=>$serviceId,'manager'=>$managerId,'starts'=>$start->format('Y-m-d H:i:s'),'id'=>$id]);respond(['ok'=>true,'status'=>'pending']);}
 requirePermission('appointments.update');$clientId=isset($d['client_id'])?entityId($d['client_id']):(int)$cur['client_id'];$serviceId=isset($d['service_id'])?entityId($d['service_id']):(int)$cur['service_id'];if($clientId===false||$serviceId===false)respond(['error'=>'Cliente o servicio inválido'],422);$start=isset($d['starts_at'])?strictDateTime(trim((string)$d['starts_at'])):new DateTimeImmutable((string)$cur['starts_at'],new DateTimeZone('America/Cancun'));if(!$start)respond(['error'=>'Fecha inválida'],422);$status=(string)($d['status']??$cur['status']);if(!in_array($status,['pending','confirmed','completed','cancelled'],true))respond(['error'=>'Estado inválido'],422);$managerRaw=array_key_exists('manager_user_id',$d)?$d['manager_user_id']:$cur['manager_user_id'];$managerId=$managerRaw===null||$managerRaw===''?null:entityId($managerRaw);if($managerId===false)respond(['error'=>'Gestor inválido'],422);ensureManager($pdo,$managerId);ensureClient($pdo,$clientId,$clientId===(int)$cur['client_id']);$duration=serviceDuration($pdo,$serviceId,$serviceId===(int)$cur['service_id']);if(in_array($status,['pending','confirmed'],true)&&hasConflict($pdo,$start,$duration,$managerId,$id))respond(['error'=>'Ese gestor ya tiene una cita en ese horario'],409);$notes=array_key_exists('notes',$d)?trim((string)$d['notes']):(string)($cur['notes']??'');$pdo->prepare('UPDATE appointments SET client_id=:client,service_id=:service,manager_user_id=:manager,starts_at=:starts,status=:status,notes=:notes WHERE id=:id')->execute(['client'=>$clientId,'service'=>$serviceId,'manager'=>$managerId,'starts'=>$start->format('Y-m-d H:i:s'),'status'=>$status,'notes'=>$notes!==''?$notes:null,'id'=>$id]);respond(['ok'=>true]);
}
if($method==='DELETE'){requirePermission('appointments.delete');$d=jsonInput();$id=entityId($d['id']??null);if($id===false)respond(['error'=>'Cita inválida'],422);try{$pdo->beginTransaction();$pdo->prepare('DELETE FROM treatments WHERE appointment_id=:id')->execute(['id'=>$id]);$s=$pdo->prepare('DELETE FROM appointments WHERE id=:id');$s->execute(['id'=>$id]);if(!$s->rowCount()){$pdo->rollBack();respond(['error'=>'La cita no existe'],404);}$pdo->commit();respond(['ok'=>true]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();respond(['error'=>'No se pudo eliminar la cita'],500);}}
respond(['error'=>'Método no permitido'],405);
