<?php

declare(strict_types=1);
require_once __DIR__.'/_bootstrap.php';
$pdo=db();$method=$_SERVER['REQUEST_METHOD']??'GET';
function serviceId(mixed $v):int|false{return filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);}
function normalizeService(array $d,array $f=[]):array{$name=trim((string)($d['name']??$f['name']??''));$description=trim((string)($d['description']??$f['description']??''));$imageUrl=trim((string)($d['image_url']??$f['image_url']??''));$duration=filter_var($d['duration_minutes']??$f['duration_minutes']??60,FILTER_VALIDATE_INT,['options'=>['min_range'=>5,'max_range'=>1440]]);$priceRaw=$d['price']??$f['price']??null;$active=array_key_exists('active',$d)?((bool)$d['active']?1:0):(int)($f['active']??1);if($name==='')respond(['error'=>'El nombre del servicio es obligatorio'],422);if(strlen($name)>140)respond(['error'=>'Nombre demasiado largo'],422);if($duration===false)respond(['error'=>'Duración inválida'],422);if($imageUrl!==''&&(strlen($imageUrl)>500||!filter_var($imageUrl,FILTER_VALIDATE_URL)))respond(['error'=>'URL de imagen inválida'],422);$price=null;if($priceRaw!==null&&$priceRaw!==''){if(!is_numeric($priceRaw))respond(['error'=>'Precio inválido'],422);$price=(float)$priceRaw;if($price<0||$price>99999999.99)respond(['error'=>'Precio fuera de rango'],422);}return ['name'=>$name,'description'=>$description!==''?$description:null,'image_url'=>$imageUrl!==''?$imageUrl:null,'duration'=>$duration,'price'=>$price,'active'=>$active];}
if($method==='GET'){$user=requirePermission('services.view');$include=$user['role']!=='client'&&(!isset($_GET['include_archived'])||$_GET['include_archived']!=='0');$sql='SELECT id,name,description,image_url,duration_minutes,price,active FROM services'.($include?'':' WHERE active=1').' ORDER BY active DESC,name';respond(['data'=>$pdo->query($sql)->fetchAll()]);}
if($method==='POST'){$user=requirePermission('services.create');$d=jsonInput();requireFields($d,['name']);$s=normalizeService($d);$q=$pdo->prepare('INSERT INTO services(name,description,image_url,duration_minutes,price,active) VALUES(:name,:description,:image_url,:duration,:price,:active)');$q->execute($s);$id=(int)$pdo->lastInsertId();auditMutation($pdo,$user,'service.created','service',$id,null,$s);respond(['id'=>$id],201);}
if($method==='PATCH'){$user=requirePermission('services.update');$d=jsonInput();$id=serviceId($d['id']??null);if($id===false)respond(['error'=>'Servicio inválido'],422);$q=$pdo->prepare('SELECT name,description,image_url,duration_minutes,price,active FROM services WHERE id=:id');$q->execute(['id'=>$id]);$cur=$q->fetch();if(!$cur)respond(['error'=>'El servicio no existe'],404);$s=normalizeService($d,$cur);$s['id']=$id;$pdo->prepare('UPDATE services SET name=:name,description=:description,image_url=:image_url,duration_minutes=:duration,price=:price,active=:active WHERE id=:id')->execute($s);$after=$s;unset($after['id']);auditMutation($pdo,$user,'service.updated','service',$id,$cur,$after);respond(['ok'=>true]);}
if($method==='DELETE'){$user=requirePermission('services.delete');$d=jsonInput();$id=serviceId($d['id']??null);if($id===false)respond(['error'=>'Servicio inválido'],422);$beforeStmt=$pdo->prepare('SELECT name,description,image_url,duration_minutes,price,active FROM services WHERE id=:id');$beforeStmt->execute(['id'=>$id]);$before=$beforeStmt->fetch();if(!$before)respond(['error'=>'El servicio no existe'],404);$q=$pdo->prepare('UPDATE services SET active=0 WHERE id=:id');$q->execute(['id'=>$id]);auditMutation($pdo,$user,'service.archived','service',$id,$before,['active'=>0]);respond(['ok'=>true,'archived'=>true]);}
respond(['error'=>'Método no permitido'],405);
