(()=>{
if(!window.solutionCan?.('payments.view')){document.querySelector('[data-view="payments"]')?.remove();return;}
const section=document.getElementById('payments'),form=document.getElementById('paymentForm'),client=document.getElementById('paymentClient'),appt=document.getElementById('paymentAppointment'),list=document.getElementById('adminPayments'),status=document.getElementById('paymentStatus');
if(!section||!form)return;
const esc=window.spaEscape||(v=>String(v??''));const method=v=>({cash:'Efectivo',card:'Tarjeta',transfer:'Transferencia',other:'Otro'}[v]||v),state=v=>({pending:'Pendiente',paid:'Pagado',refunded:'Reembolsado',cancelled:'Cancelado'}[v]||v);
async function loadClients(){const rows=await apiData('../backend/api/clients.php?per_page=200');client.innerHTML='<option value="">Selecciona cliente</option>'+rows.map(c=>`<option value="${Number(c.id)}">${esc(c.name)}</option>`).join('')}
async function loadAppointments(){appt.innerHTML='<option value="">Sin asociar a una cita</option>';if(!client.value)return;try{const rows=await apiData(`../backend/api/appointments.php?client_id=${Number(client.value)}`);appt.innerHTML+=rows.slice(0,50).map(a=>`<option value="${Number(a.id)}">${esc(String(a.starts_at).slice(0,16))} · ${esc(a.service_name||'Servicio')}</option>`).join('')}catch(e){}}
async function loadPayments(){try{const rows=await apiData('../backend/api/payments.php');list.innerHTML=rows.length?rows.map(p=>`<div class="payment-admin-row"><div><b>${esc(p.client_name||'Cliente')}</b><small>${esc(p.service_name||'Sin cita asociada')}</small></div><b>$${Number(p.amount).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2})}</b><small>${esc(method(p.method))} · ${esc(state(p.status))}</small><small>${esc(String(p.paid_at||p.created_at||'').slice(0,16))}</small></div>`).join(''):'<p class="empty-note">No hay pagos registrados.</p>'}catch(e){list.innerHTML='<p class="empty-note">No pude consultar los pagos.</p>'}}
client.addEventListener('change',loadAppointments);document.getElementById('refreshPayments')?.addEventListener('click',loadPayments);
form.addEventListener('submit',async e=>{e.preventDefault();if(!window.solutionCan?.('payments.update')){status.textContent='No tienes permiso para registrar pagos';return;}status.textContent='Registrando…';try{await postJson('../backend/api/payments.php',{client_id:Number(client.value),appointment_id:appt.value?Number(appt.value):null,amount:Number(document.getElementById('paymentAmount').value),method:document.getElementById('paymentMethod').value,status:'paid',reference:document.getElementById('paymentReference').value});status.textContent='Pago registrado ✓';document.getElementById('paymentAmount').value='';document.getElementById('paymentReference').value='';await loadPayments()}catch(err){status.textContent=err.message}});
document.querySelector('[data-view="payments"]')?.addEventListener('click',loadPayments);Promise.all([loadClients(),loadPayments()]).catch(()=>{});
})();