(()=>{
const canView=window.solutionCan?.('payments.view');
if(!canView)return;
const nav=document.querySelector('.topnav');
const main=document.querySelector('main');
if(!nav||!main||document.getElementById('paymentsAdmin'))return;
const btn=document.createElement('button');btn.type='button';btn.dataset.paymentsView='1';btn.textContent='Pagos';nav.appendChild(btn);
const section=document.createElement('section');section.id='paymentsAdmin';section.className='view';section.innerHTML=`<div class="title"><span>COBROS</span><h2>Pagos</h2><p>Registra y consulta los pagos asociados a clientes y citas.</p></div><div class="grid"><section class="panel"><div class="panelhead"><div><span>NUEVO MOVIMIENTO</span><h2>Registrar pago</h2></div></div><form id="paymentAdminForm" style="display:grid;gap:12px;padding:18px"><label>Cliente<select name="client_id" required></select></label><label>Cita <small>(opcional)</small><select name="appointment_id"><option value="">Sin asociar a cita</option></select></label><div class="row"><label>Importe<input name="amount" type="number" min="0" step="0.01" required></label><label>Método<select name="method"><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option><option value="other">Otro</option></select></label></div><label>Referencia <small>(opcional)</small><input name="reference" maxlength="120"></label><button class="save" type="submit">Registrar pago</button><p class="pilot" data-payment-status></p></form></section><section class="panel"><div class="panelhead"><div><span>HISTORIAL</span><h2>Movimientos</h2></div><small id="paymentAdminCount">0 pagos</small></div><div id="paymentAdminList"><p class="empty-note">Consultando pagos…</p></div></section></div>`;main.appendChild(section);
const form=section.querySelector('#paymentAdminForm'),clientSelect=form.elements.client_id,appointmentSelect=form.elements.appointment_id,list=section.querySelector('#paymentAdminList'),count=section.querySelector('#paymentAdminCount'),status=section.querySelector('[data-payment-status]');
const esc=window.spaEscape||(v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])));
const methodLabel=v=>({cash:'Efectivo',card:'Tarjeta',transfer:'Transferencia',other:'Otro'}[v]||v);
const statusLabel=v=>({pending:'Pendiente',paid:'Pagado',refunded:'Reembolsado',cancelled:'Cancelado'}[v]||v);
async function loadClients(){const rows=await apiData('../backend/api/clients.php?per_page=200');clientSelect.innerHTML='<option value="">Selecciona cliente</option>'+rows.map(c=>`<option value="${Number(c.id)}">${esc(c.name)}</option>`).join('')}
async function loadAppointmentsForClient(){const id=Number(clientSelect.value);appointmentSelect.innerHTML='<option value="">Sin asociar a cita</option>';if(!id)return;try{const rows=await apiData(`../backend/api/appointments.php?client_id=${id}`);appointmentSelect.innerHTML+=[...rows].sort((a,b)=>String(b.starts_at).localeCompare(String(a.starts_at))).slice(0,50).map(a=>`<option value="${Number(a.id)}">${esc(String(a.starts_at).slice(0,16))} · ${esc(a.service_name)}</option>`).join('')}catch(e){}}
async function loadPayments(){try{const rows=await apiData('../backend/api/payments.php');count.textContent=`${rows.length} ${rows.length===1?'pago':'pagos'}`;list.innerHTML=rows.length?rows.map(p=>`<div class="request-row"><div><b>${esc(p.client_name||'Cliente')}</b><small>${esc(p.service_name||'Sin cita asociada')}</small></div><span>$${Number(p.amount).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2})}</span><small>${esc(methodLabel(p.method))} · ${esc(statusLabel(p.status))}</small><small>${esc(String(p.paid_at||p.created_at||'').slice(0,16))}</small></div>`).join(''):'<p class="empty-note">No hay pagos registrados.</p>'}catch(e){list.innerHTML='<p class="empty-note">No pude consultar los pagos.</p>'}}
clientSelect.addEventListener('change',loadAppointmentsForClient);
form.addEventListener('submit',async e=>{e.preventDefault();if(!window.solutionCan?.('payments.update')){status.textContent='No tienes permiso para registrar pagos';status.className='pilot error';return}const fd=new FormData(form);status.textContent='Registrando…';status.className='pilot';try{await postJson('../backend/api/payments.php',{client_id:Number(fd.get('client_id')),appointment_id:fd.get('appointment_id')?Number(fd.get('appointment_id')):null,amount:Number(fd.get('amount')),method:String(fd.get('method')),status:'paid',reference:String(fd.get('reference')||'')});status.textContent='Pago registrado ✓';status.className='pilot success';form.elements.amount.value='';form.elements.reference.value='';await loadPayments()}catch(e){status.textContent=e.message;status.className='pilot error'}});
function openPayments(){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));section.classList.add('active');document.querySelectorAll('.topnav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');if(typeof currentView!=='undefined')currentView='payments';if(typeof addButton!=='undefined')addButton.hidden=true;loadPayments()}
btn.addEventListener('click',openPayments);document.querySelectorAll('.topnav button:not([data-payments-view])').forEach(b=>b.addEventListener('click',()=>{section.classList.remove('active');if(typeof addButton!=='undefined')addButton.hidden=false}));
Promise.all([loadClients(),loadPayments()]).catch(()=>{});
})();